export type Listing = {
    id: number;
    placeId?: string;
    rentcastId?: string;
    name: string;
    price: number;
    priceNote?: string;
    location: string;
    address?: string;
    commuteTime: number;
    commuteNote?: string;
    commuteTargetLabel?: string;
    leaseTerm: number;
    leaseNote?: string;
    numBedroom: number;
    bedroomNote?: string;
    bathrooms?: number;
    squareFootage?: number;
    daysOnMarket?: number;
    listedDate?: string;
    lastSeenDate?: string;
    furnished: boolean;
    parking: boolean;
    laundry: boolean;
    amenityNote?: string;
    matchScore?: number;
    rating?: number;
    userRatingCount?: number;
    websiteUri?: string;
    latitude?: number;
    longitude?: number;
    dataSource?: "rentcast" | "sample";
};
