const listings = [
  {
    id: 1,
    name: "The Standard Seattle",
    price: 1500,
    location: "Seattle, WA",
    commuteTime: 8,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: true,
    parking: false,
    laundry: true,
  },
  {
    id: 2,
    name: "Olive Apartments",
    price: 1650,
    location: "Seattle, WA",
    commuteTime: 12,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: true,
    laundry: true,
  },
  {
    id: 3,
    name: "HERE Seattle",
    price: 1400,
    location: "Seattle, WA",
    commuteTime: 6,
    leaseTerm: 12,
    numBedroom: 2,
    furnished: true,
    parking: false,
    laundry: true,
  },
  {
    id: 4,
    name: "Hub U District",
    price: 1550,
    location: "Seattle, WA",
    commuteTime: 5,
    leaseTerm: 12,
    numBedroom: 2,
    furnished: true,
    parking: false,
    laundry: true,
  },
  {
    id: 5,
    name: "Theory U District",
    price: 1450,
    location: "Seattle, WA",
    commuteTime: 7,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: true,
    parking: false,
    laundry: true,
  },
  {
    id: 6,
    name: "Twelve at U District",
    price: 1350,
    location: "Seattle, WA",
    commuteTime: 9,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: false,
    laundry: true,
  },
  {
    id: 7,
    name: "Identity Seattle",
    price: 1425,
    location: "Seattle, WA",
    commuteTime: 6,
    leaseTerm: 12,
    numBedroom: 2,
    furnished: true,
    parking: false,
    laundry: true,
  },
  {
    id: 8,
    name: "Nook Studios",
    price: 1200,
    location: "Seattle, WA",
    commuteTime: 15,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: false,
    laundry: true,
  },
  {
    id: 9,
    name: "AVA Ballard",
    price: 1750,
    location: "Seattle, WA",
    commuteTime: 20,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: true,
    laundry: true,
  },
  {
    id: 10,
    name: "Via6 Apartments",
    price: 1900,
    location: "Seattle, WA",
    commuteTime: 18,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: true,
    laundry: true,
  },
  {
    id: 11,
    name: "Arrive Apartments",
    price: 2100,
    location: "Seattle, WA",
    commuteTime: 17,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: true,
    laundry: true,
  },
  {
    id: 12,
    name: "Skye at Belltown",
    price: 1850,
    location: "Seattle, WA",
    commuteTime: 16,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: true,
    laundry: true,
  },
  {
    id: 13,
    name: "Harbor Steps",
    price: 2200,
    location: "Seattle, WA",
    commuteTime: 19,
    leaseTerm: 12,
    numBedroom: 2,
    furnished: false,
    parking: true,
    laundry: true,
  },
  {
    id: 14,
    name: "Cirrus Apartments",
    price: 2000,
    location: "Seattle, WA",
    commuteTime: 18,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: true,
    laundry: true,
  },
  {
    id: 15,
    name: "AMLI Mark24",
    price: 1950,
    location: "Seattle, WA",
    commuteTime: 14,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: true,
    laundry: true,
  },
  {
    id: 16,
    name: "The Danforth",
    price: 1600,
    location: "Seattle, WA",
    commuteTime: 10,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: false,
    laundry: true,
  },
  {
    id: 17,
    name: "West Edge Apartments",
    price: 2050,
    location: "Seattle, WA",
    commuteTime: 15,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: true,
    laundry: true,
  },
  {
    id: 18,
    name: "The M Seattle",
    price: 1300,
    location: "Seattle, WA",
    commuteTime: 8,
    leaseTerm: 12,
    numBedroom: 2,
    furnished: true,
    parking: false,
    laundry: true,
  },
  {
    id: 19,
    name: "Bridges @ 11th",
    price: 1250,
    location: "Seattle, WA",
    commuteTime: 11,
    leaseTerm: 12,
    numBedroom: 2,
    furnished: false,
    parking: false,
    laundry: true,
  },
  {
    id: 20,
    name: "The Accolade Apartments",
    price: 1700,
    location: "Seattle, WA",
    commuteTime: 9,
    leaseTerm: 12,
    numBedroom: 1,
    furnished: false,
    parking: true,
    laundry: true,
  },
];

export default function handler(request, response) {
  response.status(200).json(listings);
}

export function GET() {
  return Response.json(listings);
}
